# Site settings
title: "Maxime Rochkoulets"
description: "Personal website of Maxime Rochkoulets."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Maxime Rochkoulets"
resume_title:                   "Machine Learning Student"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "mrochkoulets@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       ""
resume_contact_address:         ""

resume_header_contact_info:     "(+33) 6 42 83 09 69 - mrochkoulets@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p text-align=\"justify\"><center><a href=\"https://mrochk.com/resume.pdf\">resume (pdf)</a> | <a href=\"https://github.com/mrochk\">github</a> | <a href=\"https://www.linkedin.com/in/mrochk\">linkedin</a></center><br>I'm a second year Computer Science Master's student, currently studying at KU Leuven. This website highlights a few projects I've been recently working on.<br><br><center>Master's Thesis</center><br>I am currently working on my master’s thesis on Kolmogorov–Arnold Networks and Tensor Decompositions, with a focus on using a decoupling procedure to map KANs to equivalent MLPs through the canonical polyadic decomposition (CPD).<br><br><center>Research @ GIS</center><br>In parallel, I am working remotely with the AI in Genomics research group at the Genome Institute of Singapore.<br><br>Prior to this (Summer 2025), I completed a 3-months internship in the same lab, this time on-site in Singapore, during which I developed a fast deep learning model for real-time segmentation of nanopore signals. I presented my work through a poster at the GIS25 conference. [<a href=\"https://www.linkedin.com/in/mrochk/overlay/1758610151529/single-media-viewer/?profileId=ACoAAFOfQHwBeeB83Qsy2re30TlY6C7i8R7NIGg\">poster</a>]<br><br><center>Research @ LaBRI</center><br>During summer 2024, I worked at the LaBRI (Computer Science Laboratory of Bordeaux), where I explored the use of efficient tokenizers for source code. I showed that Transformer encoders could learn classification tasks on Python source code while using up to 5 times fewer tokens than GPT3.<br><br><center>Quant Finance Student Club</center><br>Apart from that, I serve as the Head of Quant Research for the Beta Sigma Club in Leuven, a student club focused on exploring topics related to maths and quant finance that meets weekly. I am currently leading our group project in which we participate to a machine learning competition organised by the hedge fund CFM, with the goal of ranking as high as possible [<a href=\"https://www.betasigmaclub.com/team\">betasigmaclub.com</a>]<br><br><center><code>fastlob</code></center><br>In my free time, I am developing <code>fastlob</code>, an open-source limit-order-book (LOB) package in Python designed to be simple and efficient. My goal with this project is to make it the reference LOB implementation in Python. Feel free to give it a try and let me know what could be improved. [<a href=\"https://fastlob.com\">fastlob.com</a>]<br><br><center>Other</center><br>Other topics that I am currently interested to learn more about include Reinforcement Learning, Low-Level Optimization and GPU Programming.<br><br>Besides CS/ML, I like playing soccer (I joined a soccer team everywhere I've been working or studying) and hiking near my hometown in the French Pyrénées. I also like reading French and Russian literature (my favorite authors are Balzac, Camus, Dumas and Dostoevsky) and philosophy in general. Finally, I sometimes play chess online or with my friends (even tho I'm not very good at it).<br><br><center>Contact</center><br>If you would like to get in touch, feel free to use my personal email address or phone number mentioned below :)<br><br>E-mail: mrochkoulets[at]gmail[dot]com<br>Phone: (+33) 6 42 83 09 69<br></p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
# resume_section_experience:      true
# resume_section_education:       true
# resume_section_projects:        true
# resume_section_skills:          true
# resume_section_recognition:     true
# resume_section_links:           true
# resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  #resume_github_url:            "https://github.com/mrochk"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  #resume_linkedin_url:          "https://www.linkedin.com/in/mrochk"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://joelglovier.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
